language: node_js
sudo: false

env:
  - SENECA_VER=@1.x.x
  - SENECA_VER=@2.x.x
  - SENECA_VER=@3.x.x

node_js:
  - "6"
  - "4"

services:
  - mongo-server

cache:
  directories:
    - node_modules

after_script:
  npm run coverage
